# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  host: <%= Rails.application.secrets.db_host %>
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>

test:
  <<: *default
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>


beta:
  <<: *default
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>

production:
  <<: *default
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>
